server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 863340557
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 2
      max-active: 20
      # 配置获取连接等待超时的时
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      db-type: mysql
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall’用于防火墙
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mvc:
    static-path-pattern: /static/
    resources:
      static-locations: classpath:/static/

  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:templates/
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
  mail:
    host: smtp.qq.com
    username: 863340557@qq.com
    #邮箱授权码
    password: ivajsrmcwkcjbded
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttles:
            enable: true
            required: true
    default-encoding: UTF-8

#############################SpringBoot内置的配置信息，它会自动读取注入
#mybatisplus配置
mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    use-column-label: true
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql



